"""add_categories_relation_on_expense_history_and_expense_item

Revision ID: fae191b3aff9
Revises: cb8df3a5e1ad
Create Date: 2025-04-05 14:19:20.727032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'fae191b3aff9'
down_revision: Union[str, None] = 'cb8df3a5e1ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('expense_items', 'category')
    
    with op.batch_alter_table('expense_history') as batch_op:
        batch_op.alter_column('category', 
                              new_column_name='category_id',
                              type_=postgresql.UUID(as_uuid=True),
                              postgresql_using='category::uuid',
                              nullable=True)
    op.add_column('expense_history',
                  sa.Column('user_category_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key('fk_expense_history_category_id', 
                          'expense_history', 'categories',
                          ['category_id'], ['category_id'])
    op.create_foreign_key('fk_expense_history_user_category_id',
                          'expense_history', 'user_categories',
                          ['user_category_id'], ['user_category_id'])
    

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense_items', sa.Column('category', sa.String(50), nullable=True))

    op.drop_constraint('fk_expense_history_category_id', 'expense_history', type_='foreignkey')
    op.drop_constraint('fk_expense_history_user_category_id', 'expense_history', type_='foreignkey')
    op.drop_column('expense_history', 'user_category_id')

    with op.batch_alter_table('expense_history') as batch_op:
        batch_op.alter_column('category_id', new_column_name='category', type_=sa.String(50))
    # ### end Alembic commands ###
