"""add_category_related_column

Revision ID: 020b57fce03a
Revises: c1cded91876f
Create Date: 2025-06-05 16:57:47.615428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '020b57fce03a'
down_revision: Union[str, None] = 'c1cded91876f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ocr_results', sa.Column('category_id', sa.UUID(), nullable=True))
    op.add_column('ocr_results', sa.Column('user_category_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'ocr_results', 'categories', ['category_id'], ['category_id'])
    op.create_foreign_key(None, 'ocr_results', 'user_categories', ['user_category_id'], ['user_category_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ocr_results', type_='foreignkey')
    op.drop_constraint(None, 'ocr_results', type_='foreignkey')
    op.drop_column('ocr_results', 'user_category_id')
    op.drop_column('ocr_results', 'category_id')
    # ### end Alembic commands ###
