"""Set default categories

Revision ID: 557948e23e32
Revises: 8397f7f6cc78
Create Date: 2025-06-01 15:03:08.431385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '557948e23e32'
down_revision: Union[str, None] = '8397f7f6cc78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
    INSERT INTO categories (category_id, name, icon, color)
    VALUES 
        (gen_random_uuid(), 'General', 'general', '#4CAF50'),
        (gen_random_uuid(), 'Groceries', 'shopping-cart', '#4CAF50'),
        (gen_random_uuid(), 'Dining', 'utensils', '#FF9800'),
        (gen_random_uuid(), 'Transportation', 'car', '#2196F3'),
        (gen_random_uuid(), 'Utilities', 'bolt', '#FFC107'),
        (gen_random_uuid(), 'Housing', 'home', '#795548'),
        (gen_random_uuid(), 'Entertainment', 'film', '#9C27B0'),
        (gen_random_uuid(), 'Health', 'heart', '#F44336'),
        (gen_random_uuid(), 'Shopping', 'shopping-bag', '#3F51B5'),
        (gen_random_uuid(), 'Travel', 'plane', '#009688'),
        (gen_random_uuid(), 'Education', 'book', '#607D8B'),
        (gen_random_uuid(), 'Personal Care', 'user', '#E91E63'),
        (gen_random_uuid(), 'Miscellaneous', 'ellipsis-h', '#9E9E9E')
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM categories WHERE 1 = 1")
    # ### end Alembic commands ###
