"""Fix password reset token is_used field

Revision ID: 6c5fa5c39bfa
Revises: 7abfa2e3276d
Create Date: 2025-04-05 07:24:26.697286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c5fa5c39bfa'
down_revision: Union[str, None] = '7abfa2e3276d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
