"""Add password reset tokens table

Revision ID: 7abfa2e3276d
Revises: 778fbcd6bf37
Create Date: 2025-04-05 07:21:04.225941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7abfa2e3276d'
down_revision: Union[str, None] = '778fbcd6bf37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
