"""add_column_budget_name

Revision ID: c1cded91876f
Revises: 557948e23e32
Create Date: 2025-06-04 19:17:23.560508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1cded91876f'
down_revision: Union[str, None] = '557948e23e32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgets', sa.Column('budget_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budgets', 'budget_name')
    # ### end Alembic commands ###
